### ISSUE TITLE
size_matcher found a match for a large_size object with coffee_pads

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/ed_perception#14]
coffee_pads are a small object, there should be no matches if it was classified as large_size. Track da bug!

    size_matcher: 
        label: large_size
        score: 1
        hypothesis: 
            - name: coffee_pads
              score: 0.225725
        size: 
            height: 0.702156
            width: 2.52395

**Comment by rokusottervanger** [comment]
Can this be closed?

**Comment by LFBFerreira** [comment]
Lots has changed since then, this was definitely a bug but hard to recreate. So i will close it and pay attention to future tests
