### ISSUE TITLE
Exit face_detection plugin if the cascade file cannot be loaded once

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/ed_perception#16]
When I run the simulator, the following text runs through my screen. Could you fix this asap (I can't read anything in the output any more...). Please check these things (integrated, i.e., simulator but preferably for real) before pushing them to master...

[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)
[face_detector] Unable to load frontal haar cascade files (/home/amigo/ros/hydro/system/src/ed_object_models/configs/face_detector/cascade_classifiers/haarcascade_frontalface_alt_tree.xml)

**Comment by LFBFerreira** [comment]
:| this should not be happening... the haarcascade_frontalface_alt_tree.xml is indeed in the ed_object_data_models, not sure why its not loading. For the time being if you dont need the face detection, go to the config file for ED and comment out the face_detector plugin. I'll fix it first thing on monday

**Comment by LFBFerreira** [comment]
Updated the title. The error was correct since the git update was not completed, but ill change the output so that the plugin shutsdown instead of trying to load the cascade file every iteration.

**Comment by LFBFerreira** [comment]
Fixed with this commit f4c0fc79194053f77b213362b37fd9d262df13c5 , now checks if the file exists when the plugin in loaded, and it won't run the plugin if the check fails
