### ISSUE TITLE
Crash on face_recognition

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/ed_perception#17]
Apparently Fisher Faces was called without being trained. May have been caused by another entity trying to use it, since in the .CSV file there was a change in label number.

Disable a new request for learning when another is still running, and do some checking on the ID of the entity being learned maybe.

![pic-20150127131509106](https://cloud.githubusercontent.com/assets/5888635/5921771/918c36b0-a646-11e4-9dbc-2091b0e32a88.jpg)

**Comment by LFBFerreira** [comment]
Defenitly happens when a face is being learned and for some reason the segmentation fails, and a new segmented face appears on top of the entity that was previously being used by the learning.

**Comment by Rayman** [comment]
Is this still an issue?

**Comment by LFBFerreira** [comment]
Hmmm i kind of know why this happened sometimes but i was never able to reproduce it. It had to do with the fact that the "learning mode" for the face recognition plugin was ON, and suddenly a call to recognize a new face was received before the learning finished.

Given that we now use snapshooting this might not be a problem anymore, and it will unavoidably be tested in the future so i will close it.
