### ISSUE TITLE
Classification of objects adds the type new classifcation result to the set of types

### ISSUE THREAD

**Issue by rokusottervanger** [tue-robotics/ed_perception#25]
When an object is classified as a 'coke' first, and as a 'fanta' second, then 'coke' and 'fanta' are both in the types set. In the python layer, this means that entity.is_a('coke') will still return True, even though this object now has type 'fanta'.

**Comment by MatthijsBurgh** [comment]
The problem is caused by setType. This causes not only the type to be set, but also to be added to 'types'.  I suggest to add a removeTypes function to remove a type from 'types'. I don't think we should allow the current 'type'  to be removed.

**Comment by rokusottervanger** [comment]
How would the user know what type to remove then?

**Comment by MatthijsBurgh** [comment]
I haven't been very clear. I suggest the type to only be overwritten. While items in types can be removed. Which for this issue would mean:
if new_type != old_type
remove old_type from types
set type to new_type

**Comment by rokusottervanger** [comment]
Sounds good, but don't forget to also add the new type to types.

**Comment by MatthijsBurgh** [comment]
This is also done by setting the type. see https://github.com/tue-robotics/ed/blob/master/include/ed/entity.h#L37
