### ISSUE TITLE
Pointer to ED  tue::Configuration on loadConfig or loadModel headers

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/ed_perception#5]
To avoid re-reading the model.yml file in every plugin loading, do that reading once and provide an extra parameter with that information.

**Comment by LFBFerreira** [comment]
Just an update so i don't forget what i meant with this. For example for reading the configuration parameters for perception plugins only once, in the plugin_container, instead of in every perception plugin. Reduces ammount of code and loading times

**Comment by LFBFerreira** [comment]
There was already a function configure(...) for plugins that loads parameters directly from ED configuration file. All percetpion plugins now load the parameters from ED config file, no longer hardcoded, since here f4c0fc79194053f77b213362b37fd9d262df13c5
